ACCOUNT_DB: host=10.0.0.5 user=huable password=L14kMo^KklWtTVNo dbname=multiverse port=5432 sslmode=disable
JWT_KEY: fELMB#NT82ZrgxXUR8Sj0t&I@725ARLN
OAUTH2_PRIVATE_KEY: file://runtime/data/rs256-private.pem
OAUTH2_PUBLIC_KEY: file://runtime/data/rs256-public.pem
OAUTH2_JWK: file://runtime/data/rs256-jwk.json
WEB_URL: https://calieo.xyz
SELF_URL: https://calieo.xyz
MAIL_HOST: 127.0.0.1
MAIL_PORT: 587
MAIL_USER: support@multiverse.direct
MAIL_PASSWORD: nXZn*SOW6avYB^Js
MAIL_SENDER: support@multiverse.direct
RPID: portal.calieo.xyz
RPOrigins: https://calieo.xyz